@extends('layouts.app')
@section('content')
    <div class="my-2 p-3 rounded">
        <h3 class="font-bold text-center">Lorem Ipsum</h3>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ultricies lacus sit amet ultrices viverra. Mauris mollis nibh nunc, eu imperdiet est pulvinar quis. Aenean felis tellus, dictum vel sodales consequat, pellentesque vitae diam. Curabitur posuere eros ac dui cursus eleifend. Sed lacus diam, tristique vitae ipsum quis, elementum sollicitudin risus. Nulla elementum velit sit amet odio imperdiet, in consectetur risus dapibus. Nulla sed odio eu turpis tincidunt aliquet.
            Etiam velit est, gravida quis imperdiet egestas, sodales nec lacus. Vivamus semper eros a arcu tristique, at malesuada orci sagittis. Vestibulum gravida libero quis dictum congue. Quisque sit amet orci ex. Aliquam erat volutpat. Curabitur lobortis leo magna, sed dictum lacus dapibus a. Vivamus pulvinar risus quis ultricies elementum. Quisque feugiat viverra libero eu efficitur. Donec luctus, augue vitae rhoncus malesuada, est purus dignissim velit, et semper nibh arcu quis nisl. Ut purus nunc, posuere quis semper at, tincidunt a mi. Nunc non ante nec magna suscipit ultricies. Cras eu elit commodo, vestibulum mi quis, facilisis justo. Suspendisse potenti. Suspendisse potenti. Fusce ultricies tellus eget tortor dapibus, id sollicitudin augue pretium.
            Curabitur condimentum fringilla lobortis. Sed id viverra ligula, eget scelerisque augue. Ut pretium nisi eu augue lobortis, ut vestibulum libero ornare. Aenean euismod erat et leo iaculis ultrices et at lacus. In hac habitasse platea dictumst. Praesent venenatis dui ac accumsan euismod. Suspendisse ex augue, auctor id dui eu, gravida volutpat purus. Praesent nec lectus tempor, laoreet felis ut, viverra quam. Aenean nibh tellus, porta eget ante ac, tristique semper leo. Sed blandit arcu at velit iaculis, sit amet tincidunt mi sagittis. Integer a sapien dui.
        </p>
        <h3 class="font-bold text-center">1500'lerden beri kullanılan standart Lorem Ipsum pasajı</h3>
        <p>
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
        </p>
        <h3 class="text-center font-bold">M.Ö. 45 tarihinde Çiçero tarafından yazılan "de Finibus Bonorum et Malorum"un 1.10.32 sayılı bölümü</h3>
        <p>
            "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?"
        </p>
        <h3 class="font-bold text-center">1914 tarihli H. Rackham Çevirisi</h3>
        <p>
            "But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that produces no resultant pleasure?"
        </p>
        <h3 class="font-bold text-center">M.Ö. 45 tarihinde Çiçero tarafından yazılan "de Finibus Bonorum et Malorum"un 1.10.33 sayılı bölümü</h3>
        <p>
            "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat."
        </p>
    </div>
@endsection