version: "3.8"
services:
  tailwind_demo:
    container_name: tailwind_demo
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    expose:
      - 9000
    volumes:
      - .:/usr/src/app
      - ./public:/usr/src/app/public
    depends_on:
      - tailwind_demo_db
    networks:
      - app_network

  tailwind_demo_nginx:
    container_name: tailwind_demo_nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./public:/usr/src/app/public
    ports:
      - 8000:80
    depends_on:
      - tailwind_demo
    environment:
      NGINX_FPM_HOST: tailwind_demo
      NGINX_ROOT: /usr/src/app/public
    networks:
      - app_network

  tailwind_demo_db:
    container_name: tailwind_demo_db
    image: mysql:8.0.20
    restart: always
    volumes:
      - ./storage/db-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: tailwind_demo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - app_network

  tailwind_demo_redis:
    container_name: tailwind_demo_redis
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
